---
- name: Install zookeeper
  yum: name=zookeeper-server state=latest

- name: Write myid file.
  template: src=myid.j2 dest={{zookeeper_data_dir}}/myid owner=zookeeper group=zookeeper

- name: Configure zookeeper
  template: src=zoo.cfg.j2 dest={{zookeeper_conf_dir}}/zoo.cfg owner=zookeeper group=zookeeper

- name: Start zookeeper
  service: name=zookeeper-server state=restarted 
