- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: Enable EPEL repositories
  yum: name=epel-release state=present

- name: Install required packages
  yum: name={{ item }} state=latest
  with_items:
    - git
    - vim
    - tmux
    - htop
    - atop
    - iotop
    - iftop
    - wget
    - unzip
    - curl
    - java-1.8.0-openjdk-devel
    - libselinux-python
    - python-setuptools
    - python-pip
    - libgfortran

- name: Upgrade all
  yum: name=* state=latest

- name: Disable selinux
  selinux: state=disabled

- name: Disable iptables
  service: name=iptables state=stopped enabled=no

- name: Disable ip6tables
  service: name=ip6tables state=stopped enabled=no

#- name: Check java version
#  alternatives: name=java path=/usr/lib/jvm/jre-1.7.0-openjdk.x86_64/bin/java


